flowchart TD
  BOT[[BaseObjectType]]:::objecttype,abstract
  ROOT[[RobotIntentRootType]]:::objecttype
  VER[SpecificationVersion]:::variable
  CTRLS[Controllers]:::object
  CTRLT[[IntentControllerType]]:::objecttype

  BOT -->|HasSubtype| ROOT
  BOT -->|HasSubtype| CTRLT
  ROOT -->|HasProperty| VER
  ROOT --> CTRLS

  classDef object fill:#eef3fa,stroke:#444
  classDef variable fill:#eef3fa,stroke:#444
  classDef objecttype fill:#eef3fa,stroke:#444,stroke-width:2px
  classDef abstract fill:#eef3fa,stroke:#444,stroke-width:2px,font-style:italic
