stateDiagram-v2
    [*] --> Accepted
    Accepted --> Queued
    Accepted --> Executing
    Queued --> Executing
    Queued --> Cancelled
    Executing --> Suspended
    Suspended --> Executing
    Executing --> Cancelling
    Cancelling --> Cancelled
    Executing --> Succeeded
    Executing --> Failed
    Executing --> Retriable
    Retriable --> [*]
    Succeeded --> [*]
    Failed --> [*]
    Cancelled --> [*]
