from __future__ import annotations

import json
import os
import pprint
import sys
from typing import Any

import pyarrow as pa

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "_common")))
from opcua_enc import corpus, fingerprint
from opcua_enc import types as t

import arrow_codec
import build_schemas


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STD = os.path.abspath(os.path.join(ROOT, "..", "..", "arrow-encoding"))
DOC = os.path.join(STD, "OPC-UA-Part6-Arrow-DataEncoding.md")
BEGIN = "<!-- BEGIN GENERATED: type-reference -->"
END = "<!-- END GENERATED: type-reference -->"


def main() -> int:
    rendered = generate()
    with open(DOC, encoding="utf-8") as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        raise SystemExit("type-reference markers not found")
    start = text.index(BEGIN) + len(BEGIN)
    finish = text.index(END)
    new_text = text[:start] + "\n" + rendered + "\n" + text[finish:]
    with open(DOC, "w", encoding="utf-8", newline="\n") as f:
        f.write(new_text)
    return 0


def generate() -> str:
    sections = [
        "This annex is generated by `../extras/arrow-encoding/tools/gen_type_reference.py`. Do not edit between the markers.",
    ]
    for title, ty, case_name, source in _reference_items():
        case = _case(case_name)
        sections.append(_section(title, ty, case, source))
    return "\n\n".join(sections).rstrip()


def _reference_items() -> list[tuple[str, t.Type, str, str]]:
    items: list[tuple[str, t.Type, str, str]] = []
    by_builtin_case = {
        t.BuiltInType.Boolean: "bool_true",
        t.BuiltInType.SByte: "sbyte_min",
        t.BuiltInType.Byte: "byte_max",
        t.BuiltInType.Int16: "int16_min",
        t.BuiltInType.UInt16: "uint16_max",
        t.BuiltInType.Int32: "int32_max",
        t.BuiltInType.UInt32: "uint32_max",
        t.BuiltInType.Int64: "int64_max",
        t.BuiltInType.UInt64: "uint64_max",
        t.BuiltInType.Float: "float_normal",
        t.BuiltInType.Double: "double_neg_zero",
        t.BuiltInType.String: "string_unicode",
        t.BuiltInType.DateTime: "datetime_now",
        t.BuiltInType.Guid: "guid",
        t.BuiltInType.ByteString: "bytestring",
        t.BuiltInType.XmlElement: "xml",
        t.BuiltInType.NodeId: "nodeid_guid",
        t.BuiltInType.ExpandedNodeId: "expnodeid_full",
        t.BuiltInType.StatusCode: "status_bad",
        t.BuiltInType.QualifiedName: "qname",
        t.BuiltInType.LocalizedText: "ltext_full",
        t.BuiltInType.ExtensionObject: "extobj_point",
        t.BuiltInType.DataValue: "datavalue_full",
        t.BuiltInType.Variant: "variant_int",
        t.BuiltInType.DiagnosticInfo: "diaginfo_nested",
    }
    for bid in t.BuiltInType:
        items.append((f"Built-in {bid.name}", t.Builtin(bid), by_builtin_case[bid], "schemas\\base.json builtins"))
    items.extend([
        ("Composite Array<String>", t.Array(t.STRING), "array_string_with_nulls", "schemas\\base.json corpusTypes"),
        ("Composite Matrix<Double>", t.Matrix(t.DOUBLE), "matrix_double_2x2_special", "schemas\\base.json matrix/corpusTypes"),
        ("Composite plain Structure Point", corpus.POINT, "struct_point", "../extras/arrow-encoding/schemas/struct-Point.json"),
        ("Composite StructureWithOptionalFields Person", corpus.PERSON, "struct_person_present_null", "../extras/arrow-encoding/schemas/struct-Person.json"),
        ("Composite dense Union Measurement", corpus.MEASUREMENT, "union_text_null", "../extras/arrow-encoding/schemas/struct-Measurement.json"),
        ("Worked structured DataType Envelope", corpus.ENVELOPE, "envelope", "../extras/arrow-encoding/schemas/struct-Envelope.json"),
    ])
    return items


def _section(title: str, ty: t.Type, case: corpus.Case, source: str) -> str:
    data_type = _published_arrow_type(title, case)
    canonical_type = arrow_codec.canonical_type_to_arrow(ty)
    if not data_type.equals(canonical_type):
        raise AssertionError(f"published schema for {title} drifts from canonical codec type")
    schema = pa.schema([pa.field("value", data_type)], metadata={b"opcua-arrow": b"1"})
    schema_bytes = schema.serialize().to_pybytes()
    return "\n\n".join([
        f"### {title}",
        f"Published schema source: `{source}`. SchemaId: `{fingerprint.sha256_id_hex(schema_bytes, build_schemas.ARROW_SCHEMAID_BYTES)}`.",
        _structure_table(data_type),
        "Arrow schema:",
        f"```text\n{schema.to_string()}\n```",
        "Example value:",
        f"```text\n{pprint.pformat(case.value, sort_dicts=True)}\n```",
    ])


def _structure_table(data_type: pa.DataType) -> str:
    rows = ["| Field | Arrow DataType | Nullable/validity | Notes |", "|---|---|---|---|"]
    for path, field, notes in _walk_fields("value", pa.field("value", data_type), top=True):
        rows.append(f"| `{path}` | `{field.type}` | {'nullable' if field.nullable else 'not nullable'}; Arrow validity bitmap when needed | {notes} |")
    return "\n".join(rows)


def _walk_fields(path: str, field: pa.Field, *, top: bool = False) -> list[tuple[str, pa.Field, str]]:
    dt = field.type
    notes = _notes(dt, path)
    rows = [(path, field, notes)]
    if pa.types.is_struct(dt):
        for child in dt:
            rows.extend(_walk_fields(f"{path}.{child.name}", child))
    elif pa.types.is_list(dt) or pa.types.is_large_list(dt):
        rows.extend(_walk_fields(f"{path}[]", dt.value_field))
    elif pa.types.is_union(dt):
        for child in dt:
            rows.extend(_walk_fields(f"{path}.{child.name}", child))
    return rows if top or len(rows) <= 80 else rows[:80] + [(f"{path}.…", pa.field("truncated", pa.null()), "Nested field list abbreviated for compactness.")]


def _notes(dt: pa.DataType, path: str) -> str:
    if pa.types.is_union(dt):
        return "Dense-union type id plus value offset selects the active branch."
    if pa.types.is_struct(dt) and path.endswith(("Email", "Nickname")):
        return "`present` distinguishes absent optional fields from present null values."
    if pa.types.is_list(dt):
        return "List offsets identify the element range; null list differs from empty list."
    if pa.types.is_fixed_size_binary(dt):
        return "Fixed-width bytes."
    return "Canonical Part 6 Arrow mapping."


def _case(name: str) -> corpus.Case:
    by_name = {c.name: c for c in corpus.CORPUS}
    return by_name[name]


def _published_arrow_type(title: str, case: corpus.Case) -> pa.DataType:
    if title.startswith("Built-in "):
        name = title.removeprefix("Built-in ")
        with open(os.path.join(STD, "schemas", "base.json"), encoding="utf-8") as f:
            return _arrow_from_detail(json_load(f)["builtins"][name]["detail"])
    if title.endswith("Point") or title.endswith("Person") or title.endswith("Measurement") or title.endswith("Envelope"):
        struct_name = title.split()[-1]
        with open(os.path.join(ROOT, "schemas", f"struct-{struct_name}.json"), encoding="utf-8") as f:
            return _arrow_from_detail(json_load(f)["arrow"]["detail"])
    with open(os.path.join(STD, "schemas", "base.json"), encoding="utf-8") as f:
        return _arrow_from_detail(json_load(f)["corpusTypes"][case.name]["detail"])


def json_load(f: Any) -> Any:
    return json.load(f)


def _arrow_from_detail(detail: Any) -> pa.DataType:
    if isinstance(detail, dict):
        kind = detail["type"]
        if kind == "struct":
            return pa.struct([pa.field(f["name"], _arrow_from_detail(f["type"]), nullable=f.get("nullable", True)) for f in detail["fields"]])
        if kind == "list":
            return pa.list_(pa.field("item", _arrow_from_detail(detail["value"]), nullable=detail.get("valueNullable", True)))
        if kind == "dense_union":
            return pa.union([pa.field(f["name"], _arrow_from_detail(f["type"])) for f in detail["fields"]], mode="dense", type_codes=detail.get("typeCodes"))
        raise ValueError(f"unknown Arrow detail kind {kind}")
    return _primitive_arrow(str(detail))


def _primitive_arrow(name: str) -> pa.DataType:
    primitives = {
        "null": pa.null(), "bool": pa.bool_(), "int8": pa.int8(), "uint8": pa.uint8(),
        "int16": pa.int16(), "uint16": pa.uint16(), "int32": pa.int32(), "uint32": pa.uint32(),
        "int64": pa.int64(), "uint64": pa.uint64(), "float": pa.float32(), "double": pa.float64(),
        "string": pa.utf8(), "binary": pa.binary(), "fixed_size_binary[16]": pa.binary(16),
    }
    if name not in primitives:
        raise ValueError(f"unknown primitive Arrow type {name}")
    return primitives[name]


if __name__ == "__main__":
    raise SystemExit(main())
