#!/usr/bin/env bash
#
# Renders a figure exported from a Word master - a Visio drawing or a PowerPoint slide - to the
# SVG the specification embeds, using LibreOffice. The Linux and macOS half of a pair: the
# Windows half is office-to-svg.ps1, which drives Visio and PowerPoint themselves.
#
# Named together, one manifest entry, and the same entry for every author who clones the
# repository:
#
#     "figureGenerators": {
#       ".vsdx": { "win": "tools/office-to-svg.ps1", "default": "tools/office-to-svg.sh" },
#       ".pptx": { "win": "tools/office-to-svg.ps1", "default": "tools/office-to-svg.sh" }
#     }
#
# `win` and `default` rather than a script chosen by whoever is running: written down once, it
# is the same for everybody and there is nothing to edit after a clone. Deliberately NOT
# something the tool detects for itself - a repository where the engine follows the author is a
# repository whose figures change appearance according to who regenerated last, and the .svg is
# committed, so that is a whole-file diff on a figure nobody touched.
#
# The two engines do render differently, and this pairing accepts that in exchange for every
# author being able to regenerate a figure at all. What keeps it manageable is that a figure is
# normally regenerated by whoever is editing it, so a diagram tends to stay with one engine;
# what to watch for is a figure that rewrites itself whole when somebody else touches it.
#
# Requires libreoffice (the Draw and Impress filters are packaged separately on some
# distributions):
#
#     sudo apt install libreoffice-draw libreoffice-impress inkscape \
#                      fonts-crosextra-carlito fonts-crosextra-caladea
#
# The fonts are not optional in practice. These diagrams were drawn in Calibri and Cambria; with
# neither those nor their metric-compatible substitutes installed, LibreOffice reflows every
# label and the text drifts out of the boxes it was placed in. Carlito and Caladea are the
# substitutes, and they are what makes the rendering come out the size it was drawn. macOS has
# Calibri and Cambria already if Office is installed there, and substitutes otherwise.
#
# inkscape is optional and does one thing here - see the crop step below.
#
# Called as `<script> <source> <svg>` from the repository root.

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: office-to-svg.sh <source> <svg>" >&2
    exit 2
fi

source_path=$1
svg_path=$2

if [ ! -f "$source_path" ]; then
    echo "no such figure source: $source_path" >&2
    exit 1
fi

# Both paths are made absolute before anything else. LibreOffice is run with --outdir into a
# temporary directory rather than in place, so a relative source would be resolved against a
# working directory that is about to stop being the interesting one; `update` passes absolute
# paths already, and a person running this by hand passes whatever they typed.
source_path=$(cd "$(dirname "$source_path")" && pwd)/$(basename "$source_path")

svg_directory=$(dirname "$svg_path")
mkdir -p "$svg_directory"
svg_path=$(cd "$svg_directory" && pwd)/$(basename "$svg_path")

# On macOS soffice is inside the application bundle and is not on the PATH, which is exactly the
# kind of thing that otherwise becomes an exported SOFFICE in one person's shell profile - a
# private edit, and the repository stops building for anyone who has not made it.
soffice=${SOFFICE:-}
if [ -z "$soffice" ]; then
    for candidate in \
        soffice \
        libreoffice \
        /Applications/LibreOffice.app/Contents/MacOS/soffice \
        "$HOME/Applications/LibreOffice.app/Contents/MacOS/soffice" \
        /usr/lib/libreoffice/program/soffice \
        /snap/bin/libreoffice
    do
        if command -v "$candidate" >/dev/null 2>&1; then
            soffice=$candidate
            break
        fi
    done
fi
if [ -z "$soffice" ]; then
    echo "LibreOffice is not installed, and this generator renders with it. Install it from" >&2
    echo "https://www.libreoffice.org/download/ - on Debian and Ubuntu, apt install" >&2
    echo "libreoffice-draw libreoffice-impress - or set SOFFICE to its path." >&2
    exit 1
fi

name=$(basename "$source_path")
stem=${name%.*}
extension=$(printf '%s' "${name##*.}" | tr '[:upper:]' '[:lower:]')

case "$extension" in
    vsd|vsdx|vsdm) kind=Visio ;;
    ppt|pptx|pptm) kind=PowerPoint ;;
    *)
        echo "Cannot render $name: this generator renders Visio (.vsdx) and PowerPoint (.pptx)" >&2
        echo "figures. Map another extension to a generator of its own in manifest.json." >&2
        exit 1
        ;;
esac

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# Only the first page or slide is rendered, which matches what the Windows generator does and
# what a figure is. Saying so costs a zip listing on the formats that are zips; a legacy .vsd or
# .ppt is a compound binary and goes unchecked rather than being opened twice to count.
if command -v unzip >/dev/null 2>&1; then
    case "$extension" in
        vsdx|vsdm) pattern='^visio/pages/page[0-9]+\.xml$' ;;
        pptx|pptm) pattern='^ppt/slides/slide[0-9]+\.xml$' ;;
        *)         pattern='' ;;
    esac
    if [ -n "$pattern" ]; then
        count=$(unzip -Z1 "$source_path" 2>/dev/null | grep -cE "$pattern" || true)
        if [ "${count:-0}" -gt 1 ]; then
            echo "warning: $name has $count pages; only the first is exported."
        fi
    fi
fi

# -env:UserInstallation is the load-bearing argument. Without a profile of its own, a headless
# soffice hands the job to whatever LibreOffice the author already has open on their desktop and
# returns immediately, having written nothing - which reads as a renderer that silently does not
# work rather than as a conflict, and is the single most common way this fails. A profile per
# run also means two figures can render at once.
run_soffice() {
    local filter=$1
    rm -rf "$work/out"
    mkdir -p "$work/out"
    "$soffice" \
        -env:UserInstallation="file://$work/profile" \
        --headless --norestore --nolockcheck --nodefault --nofirststartwizard \
        --convert-to "$filter" --outdir "$work/out" "$source_path" \
        >"$work/soffice.log" 2>&1 || true
    [ -f "$work/out/$stem.svg" ]
}

# draw_svg_Export rather than the svg default, and for both formats. Asked for plain "svg" a
# .pptx goes through Impress's exporter, which writes the whole deck into one file with
# JavaScript to page between the slides - a working slideshow, and not a figure. Draw's exporter
# writes one drawing as one picture, which is what is wanted. It is the default filter for the
# Visio side either way, named explicitly so both paths are the same path.
if ! run_soffice "svg:draw_svg_Export"; then
    if ! run_soffice svg; then
        echo "LibreOffice wrote no SVG for $name. Its output was:" >&2
        sed 's/^/    /' "$work/soffice.log" >&2
        echo "If it says nothing at all, the import filter for $kind files is probably not" >&2
        echo "installed: apt install libreoffice-draw libreoffice-impress." >&2
        exit 1
    fi
fi

produced=$work/out/$stem.svg

# The Impress exporter is the fallback's failure mode, so it is checked for rather than assumed
# away. Its output renders as the first slide and is a presentation - stripping the script would
# leave every slide stacked in one picture, so this reports it instead of quietly shipping it.
if grep -q '<script' "$produced"; then
    echo "This LibreOffice would not apply the Draw exporter to $name, and the presentation" >&2
    echo "exporter it used writes the whole deck with slide navigation rather than one figure." >&2
    echo "LibreOffice 7.0 and newer accept draw_svg_Export." >&2
    exit 1
fi

# Crop to the drawing. LibreOffice exports the page, and a slide is a 16:9 canvas with the
# diagram adrift somewhere in it - the same reason the Windows generator exports the shape range
# and not the slide. Inkscape is what can compute the drawing's extent, and it is not a
# dependency worth insisting on, so a machine without it gets a correct figure with whitespace
# around it and is told which one it got.
inkscape=${INKSCAPE:-}
if [ -z "$inkscape" ]; then
    for candidate in inkscape /Applications/Inkscape.app/Contents/MacOS/inkscape; do
        if command -v "$candidate" >/dev/null 2>&1; then
            inkscape=$candidate
            break
        fi
    done
fi

if [ "${OFFICE_TO_SVG_NO_CROP:-}" = "1" ]; then
    :
elif [ -n "$inkscape" ]; then
    cropped=$work/cropped.svg
    # Inkscape 1.x first, then the 0.92 spelling of the same two operations.
    if "$inkscape" --export-type=svg --export-plain-svg --export-area-drawing \
                   --export-filename="$cropped" "$produced" >/dev/null 2>&1 && [ -s "$cropped" ]; then
        produced=$cropped
    elif "$inkscape" --export-area-drawing --export-plain-svg="$cropped" "$produced" \
                   >/dev/null 2>&1 && [ -s "$cropped" ]; then
        produced=$cropped
    else
        echo "warning: inkscape could not crop $stem.svg; it keeps the page margins."
    fi
else
    echo "note: inkscape is not installed, so $stem.svg is the whole page rather than the"
    echo "      drawing. apt install inkscape to crop it."
fi

# Written over the target only now, and by a move rather than by having been the target all
# along: a run that fails half way leaves the committed figure as it was instead of truncated.
mv -f "$produced" "$svg_path"

printf 'wrote %s (%s bytes)\n' "$svg_path" "$(stat -c %s "$svg_path" 2>/dev/null || stat -f %z "$svg_path")"
