<#
.SYNOPSIS
    Renders a figure exported from a Word master - a Visio drawing or a PowerPoint slide -
    to the SVG the specification embeds.

.DESCRIPTION
    Migrating a Word specification to markdown saves each embedded OLE object as the file it
    really is: a .vsdx, a .pptx. That file stays the source of truth for its figure until the
    working group redraws the diagram in draw.io, so it is committed and this script produces
    the .svg beside it.

    Wired into manifest.json as a figureGenerator, so it runs from `update --write` and never
    from a build. Where every author is on Windows, that is one script named once:

        "figureGenerators": {
          ".vsdx": "tools/office-to-svg.ps1",
          ".pptx": "tools/office-to-svg.ps1"
        }

    and where they are not, it is named for the platform it runs on, beside the one that
    renders the same figure everywhere else:

        "figureGenerators": {
          ".vsdx": { "win": "tools/office-to-svg.ps1", "default": "tools/office-to-svg.sh" },
          ".pptx": { "win": "tools/office-to-svg.ps1", "default": "tools/office-to-svg.sh" }
        }

    A build reads the committed .svg and executes nothing - which is the point. Rendering a
    Visio drawing needs Visio, and a build that shelled out to it would succeed on the author's
    machine and fail in CI, or worse, quietly produce something different.

    This one drives the Office applications installed on a Windows machine, and it is the
    highest-fidelity path: the same application that drew the diagram writes the SVG.
    office-to-svg.sh is the other half of the pair and renders with LibreOffice, which is what
    a Linux or macOS author has. The two do render differently, so a figure regenerated by
    somebody on the other platform can come back as a whole-file diff; that is the cost of
    every author being able to regenerate a figure at all, and it is why the pairing is written
    down in the manifest rather than detected - written down, it is the same for everybody.

.NOTES
    Called as `<script> <source> <svg>` from the repository root.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)][string] $Source,
    [Parameter(Mandatory = $true, Position = 1)][string] $Svg
)

$ErrorActionPreference = 'Stop'

$Source = (Resolve-Path -LiteralPath $Source).Path

# Both paths are made absolute before anything else: Export is COM, so it resolves a relative
# path against the Office application's own working directory rather than this script's, and
# the file lands somewhere nobody looks. `update` passes absolute paths already, and a person
# running this by hand passes whatever they typed.
if (-not [System.IO.Path]::IsPathRooted($Svg)) {
    $Svg = Join-Path (Get-Location).Path $Svg
}
$Svg = [System.IO.Path]::GetFullPath($Svg)

$svgDirectory = Split-Path -Parent $Svg
if ($svgDirectory -and -not (Test-Path -LiteralPath $svgDirectory)) {
    New-Item -ItemType Directory -Path $svgDirectory -Force | Out-Null
}

# Export writes a new file rather than replacing one in place, and Visio prompts about an
# existing name instead of failing - which in a non-interactive run is a hang, not an error.
if (Test-Path -LiteralPath $Svg) { Remove-Item -LiteralPath $Svg -Force }

function Convert-Visio {
    param([string] $Source, [string] $Svg)

    # Visio.InvisibleApp, not Visio.Application. The Application ProgID starts Visio with its
    # window shown and setting Visible afterwards only takes it away again - which is the
    # window that appears for about a second on every figure. InvisibleApp is the same
    # automation object started hidden, so there is nothing to hide.
    #
    # Registered by every Visio since 2002, but falling back costs three lines and the fallback
    # is exactly what this used to do, so a Visio that does not offer it renders as before
    # rather than failing.
    try {
        $visio = New-Object -ComObject Visio.InvisibleApp
    }
    catch [System.Runtime.InteropServices.COMException] {
        $visio = New-Object -ComObject Visio.Application
    }

    try {
        $visio.Visible = $false
        # Answer every dialog with its default. One prompt nobody sees is an automated run
        # that never returns.
        $visio.AlertResponse = 1

        # visOpenRO (2) + visOpenDocked (4): read-only so the source cannot be modified by
        # having been rendered, and docked so no separate window is created.
        $document = $visio.Documents.OpenEx($Source, 2 + 4)
        try {
            if ($document.Pages.Count -gt 1) {
                Write-Warning ("{0} has {1} pages; only the first is exported." -f `
                    (Split-Path -Leaf $Source), $document.Pages.Count)
            }
            $document.Pages.Item(1).Export($Svg)
        }
        finally {
            $document.Close()
        }
    }
    finally {
        $visio.AlertResponse = 0
        $visio.Quit()
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($visio) | Out-Null
    }
}

function Convert-PowerPoint {
    param([string] $Source, [string] $Svg)

    # PowerPoint has no invisible ProgID and refuses Application.Visible = msoFalse outright,
    # so the presentation being opened WithWindow = msoFalse is the whole of what can be done
    # about it. Recent builds honour that and show nothing; some older ones still flash the
    # application frame once, and there is no supported way to stop them.
    $powerpoint = New-Object -ComObject PowerPoint.Application
    try {
        # msoTrue = -1, msoFalse = 0. Opened read-only, untitled false, with no window.
        $presentation = $powerpoint.Presentations.Open($Source, -1, 0, 0)
        try {
            $slide = $presentation.Slides.Item(1)
            if ($slide.Shapes.Count -eq 0) {
                throw "$Source has no shapes on its first slide."
            }

            # The shapes, not the slide. A slide exports as a page - the diagram adrift in a
            # 16:9 canvas of whitespace - and the figure is the drawing. Exporting the shape
            # range crops to what was actually drawn.
            #
            # 6 is ppShapeFormatSVG; 1 is ppRelativeToSlide, so a shape keeps the size it has
            # on the slide rather than being scaled to some other box.
            $slide.Shapes.Range().Export($Svg, 6, 0, 0, 1)
        }
        finally {
            $presentation.Close()
        }
    }
    finally {
        $powerpoint.Quit()
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($powerpoint) | Out-Null
    }
}

switch -Regex ([System.IO.Path]::GetExtension($Source)) {
    '^\.vsd[xm]?$' { Convert-Visio      -Source $Source -Svg $Svg }
    '^\.ppt[xm]?$' { Convert-PowerPoint -Source $Source -Svg $Svg }
    default {
        throw ("Cannot render {0}: this generator renders Visio (.vsdx) and PowerPoint " +
               "(.pptx) figures. Map another extension to a generator of its own in " +
               "manifest.json." -f (Split-Path -Leaf $Source))
    }
}

if (-not (Test-Path -LiteralPath $Svg)) {
    throw "The export reported success but wrote no $Svg."
}

Write-Output ("wrote {0} ({1:N0} bytes)" -f $Svg, (Get-Item -LiteralPath $Svg).Length)
