from __future__ import annotations

import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SCHEMAS = ROOT / "schemas"
STD = (HERE / ".." / ".." / ".." / "protobuf-encoding").resolve()
STD_SCHEMAS = STD / "schemas"
sys.path.insert(0, os.path.abspath(HERE / ".." / ".." / "_common"))
from opcua_enc import corpus, nodeset, types as t  # noqa: E402

BUILTINS_PROTO = 'syntax = "proto3";\n\npackage opcua.protobuf.v1;\n\nimport "google/protobuf/any.proto";\n\nmessage BooleanValue { bool value = 1; }\nmessage SByteValue { int32 value = 1; }\nmessage ByteValue { uint32 value = 1; }\nmessage Int16Value { int32 value = 1; }\nmessage UInt16Value { uint32 value = 1; }\nmessage Int32Value { int32 value = 1; }\nmessage UInt32Value { uint32 value = 1; }\nmessage Int64Value { int64 value = 1; }\nmessage UInt64Value { uint64 value = 1; }\nmessage FloatValue { float value = 1; }\nmessage DoubleValue { double value = 1; }\nmessage StringValue { optional string value = 1; }\nmessage DateTimeValue { sfixed64 ticks = 1; }\nmessage GuidValue { bytes value = 1; }\nmessage ByteStringValue { optional bytes value = 1; }\nmessage XmlElementValue { optional string value = 1; }\nmessage StatusCodeValue { fixed32 value = 1; }\n\nmessage NodeId {\n  enum IdType {\n    NUMERIC = 0;\n    STRING = 1;\n    GUID = 2;\n    OPAQUE = 3;\n  }\n  uint32 namespace = 1;\n  IdType id_type = 2;\n  oneof identifier {\n    uint32 numeric = 3;\n    string string = 4;\n    bytes guid = 5;\n    bytes opaque = 6;\n  }\n}\n\nmessage ExpandedNodeId {\n  NodeId node_id = 1;\n  optional string namespace_uri = 2;\n  uint32 server_index = 3;\n}\n\nmessage QualifiedName {\n  uint32 namespace = 1;\n  optional string name = 2;\n}\n\nmessage LocalizedText {\n  optional string locale = 1;\n  optional string text = 2;\n}\n\nmessage ArrayValue {\n  // Each element is a wrapper. An empty Value is the canonical null element.\n  repeated Value values = 1;\n}\n\nmessage MatrixValue {\n  repeated int32 dimensions = 1;\n  // Row-major values; nullable element values are represented by empty Value wrappers.\n  repeated Value values = 2;\n}\n\nmessage ExtensionObject {\n  NodeId type_id = 1;\n  oneof body {\n    google.protobuf.Any message_body = 2;\n    bytes opaque = 3;\n  }\n}\n\nmessage Variant {\n  // BuiltInType numeric id. Absence means a null Variant.\n  optional uint32 built_in_type = 1;\n  oneof payload {\n    Value scalar = 2;\n    ArrayValue array = 3;\n    MatrixValue matrix = 4;\n  }\n}\n\nmessage DataValue {\n  Variant value = 1;\n  optional fixed32 status = 2;\n  optional sfixed64 source_timestamp = 3;\n  optional uint32 source_picoseconds = 4;\n  optional sfixed64 server_timestamp = 5;\n  optional uint32 server_picoseconds = 6;\n}\n\nmessage DiagnosticInfo {\n  optional int32 symbolic_id = 1;\n  optional int32 namespace_uri = 2;\n  optional int32 locale = 3;\n  optional int32 localized_text = 4;\n  optional string additional_info = 5;\n  optional fixed32 inner_status_code = 6;\n  DiagnosticInfo inner_diagnostic_info = 7;\n}\n\nmessage Value {\n  oneof kind {\n    bool boolean_value = 1;\n    int32 sbyte_value = 2;\n    uint32 byte_value = 3;\n    int32 int16_value = 4;\n    uint32 uint16_value = 5;\n    int32 int32_value = 6;\n    uint32 uint32_value = 7;\n    int64 int64_value = 8;\n    uint64 uint64_value = 9;\n    float float_value = 10;\n    double double_value = 11;\n    string string_value = 12;\n    sfixed64 datetime_value = 13;\n    bytes guid_value = 14;\n    bytes bytestring_value = 15;\n    XmlElementValue xml_element_value = 16;\n    NodeId node_id_value = 17;\n    ExpandedNodeId expanded_node_id_value = 18;\n    fixed32 status_code_value = 19;\n    QualifiedName qualified_name_value = 20;\n    LocalizedText localized_text_value = 21;\n    ExtensionObject extension_object_value = 22;\n    DataValue data_value = 23;\n    Variant variant_value = 24;\n    DiagnosticInfo diagnostic_info_value = 25;\n    ArrayValue array_value = 26;\n    MatrixValue matrix_value = 27;\n    google.protobuf.Any message_value = 28;\n    int32 enum_value = 30;\n  }\n}\n'

HEADER = "// Generated by tools/build_schemas.py. Do not edit.\n"


def _safe_name(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not s or s[0].isdigit():
        s = "_" + s
    return s


def _field_name(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s).lower()
    return _safe_name(s)


def _proto_scalar(ty: t.Type) -> tuple[str, bool]:
    if isinstance(ty, t.Enumeration):
        return ("uint32" if ty.is_option_set else "int32", False)
    if isinstance(ty, t.Builtin):
        b = ty.id
        m = {
            t.BuiltInType.Boolean: ("bool", False),
            t.BuiltInType.SByte: ("int32", False),
            t.BuiltInType.Byte: ("uint32", False),
            t.BuiltInType.Int16: ("int32", False),
            t.BuiltInType.UInt16: ("uint32", False),
            t.BuiltInType.Int32: ("int32", False),
            t.BuiltInType.UInt32: ("uint32", False),
            t.BuiltInType.Int64: ("int64", False),
            t.BuiltInType.UInt64: ("uint64", False),
            t.BuiltInType.Float: ("float", False),
            t.BuiltInType.Double: ("double", False),
            t.BuiltInType.String: ("opcua.protobuf.v1.StringValue", True),
            t.BuiltInType.DateTime: ("sfixed64", False),
            t.BuiltInType.Guid: ("bytes", False),
            t.BuiltInType.ByteString: ("opcua.protobuf.v1.ByteStringValue", True),
            t.BuiltInType.XmlElement: ("opcua.protobuf.v1.XmlElementValue", True),
            t.BuiltInType.NodeId: ("opcua.protobuf.v1.NodeId", False),
            t.BuiltInType.ExpandedNodeId: ("opcua.protobuf.v1.ExpandedNodeId", False),
            t.BuiltInType.StatusCode: ("fixed32", False),
            t.BuiltInType.QualifiedName: ("opcua.protobuf.v1.QualifiedName", False),
            t.BuiltInType.LocalizedText: ("opcua.protobuf.v1.LocalizedText", False),
            t.BuiltInType.ExtensionObject: ("opcua.protobuf.v1.ExtensionObject", False),
            t.BuiltInType.DataValue: ("opcua.protobuf.v1.DataValue", False),
            t.BuiltInType.Variant: ("opcua.protobuf.v1.Variant", False),
            t.BuiltInType.DiagnosticInfo: ("opcua.protobuf.v1.DiagnosticInfo", False),
        }
        return m[b]
    if isinstance(ty, t.Struct):
        return f"opcua.protobuf.generated.{_safe_name(ty.name)}", False
    return "opcua.protobuf.v1.Value", False


def _needs_proto3_optional(ty: t.Type) -> bool:
    if isinstance(ty, t.Enumeration):
        return True
    if not isinstance(ty, t.Builtin):
        return False
    return ty.id in {
        t.BuiltInType.Boolean,
        t.BuiltInType.SByte,
        t.BuiltInType.Byte,
        t.BuiltInType.Int16,
        t.BuiltInType.UInt16,
        t.BuiltInType.Int32,
        t.BuiltInType.UInt32,
        t.BuiltInType.Int64,
        t.BuiltInType.UInt64,
        t.BuiltInType.Float,
        t.BuiltInType.Double,
        t.BuiltInType.DateTime,
        t.BuiltInType.Guid,
        t.BuiltInType.StatusCode,
    }


def _type_line(ty: t.Type, fld: t.Field, number: int) -> str:
    name = _field_name(fld.name)
    if isinstance(ty, t.Array):
        return f"  opcua.protobuf.v1.ArrayValue {name} = {number};"
    if isinstance(ty, t.Matrix):
        return f"  opcua.protobuf.v1.MatrixValue {name} = {number};"
    elem, nullable = _proto_scalar(ty)
    prefix = "optional " if fld.is_optional and (nullable or _needs_proto3_optional(ty)) else ""
    return f"  {prefix}{elem} {name} = {number};"


def _deps_for_type(ty: t.Type) -> set[str]:
    if isinstance(ty, t.Struct):
        return {f"{_safe_name(ty.name).lower()}.proto"}
    if isinstance(ty, (t.Array, t.Matrix)):
        return _deps_for_type(ty.element)
    return set()


def _deps_for_struct(st: t.Struct) -> set[str]:
    own = f"{_safe_name(st.name).lower()}.proto"
    deps: set[str] = set()
    for fld in st.fields:
        deps.update(_deps_for_type(fld.type))
    deps.discard(own)
    return deps


def _enum_proto(enum: t.Enumeration) -> str:
    msg = _safe_name(enum.name)
    if enum.is_option_set:
        return f"message {msg}OptionSet {{\n  uint32 bits = 1;\n}}\n"
    lines = [f"enum {msg} {{"]
    if not any(m.value == 0 for m in enum.members):
        lines.append(f"  {msg.upper()}_UNSPECIFIED = 0;")
    used: set[str] = set()
    for m in enum.members:
        n = _safe_name(m.name).upper()
        if not n.startswith(msg.upper()):
            n = f"{msg.upper()}_{n}"
        while n in used:
            n += "_"
        used.add(n)
        lines.append(f"  {n} = {m.value};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _struct_proto(st: t.Struct) -> str:
    msg = _safe_name(st.name)
    if st.kind == t.StructureKind.UNION:
        lines = [f"message {msg} {{", "  oneof value {"]
        for i, fld in enumerate(st.fields, 1):
            elem, _ = _proto_scalar(fld.type)
            lines.append(f"    {elem} {_field_name(fld.name)} = {i};")
        lines += ["  }", "}"]
        return "\n".join(lines) + "\n"
    lines = [f"message {msg} {{"]
    for i, fld in enumerate(st.fields, 1):
        lines.append(_type_line(fld.type, fld, i))
    lines.append("}")
    return "\n".join(lines) + "\n"


def _write_type_file(name: str, body: str, imports: set[str] | None = None) -> None:
    import_lines = ['import "opcua_builtins.proto";']
    import_lines += [f'import "{imp}";' for imp in sorted(imports or set())]
    text = HEADER + 'syntax = "proto3";\n\npackage opcua.protobuf.generated;\n\n' + "\n".join(import_lines) + "\n\noption java_multiple_files = true;\n\n" + body
    (SCHEMAS / f"{_safe_name(name).lower()}.proto").write_text(text, encoding="utf-8", newline="\n")


def collect_types() -> tuple[list[t.Struct], list[t.Enumeration]]:
    structs = list(corpus.STRUCT_TYPES)
    enums = list(corpus.ENUM_TYPES)
    ns_path = STD.parent / "pubsub-binding" / "Opc.Ua.PubSubBinding.NodeSet2.xml"
    if ns_path.exists():
        res = nodeset.load_datatypes(str(ns_path))
        by_struct = {s.name: s for s in structs}
        by_enum = {e.name: e for e in enums}
        for s in res.structs:
            by_struct.setdefault(s.name, s)
        for e in res.enums:
            by_enum.setdefault(e.name, e)
        structs = [by_struct[k] for k in sorted(by_struct)]
        enums = [by_enum[k] for k in sorted(by_enum)]
    return structs, enums


def main() -> int:
    SCHEMAS.mkdir(parents=True, exist_ok=True)
    STD_SCHEMAS.mkdir(parents=True, exist_ok=True)
    for old in SCHEMAS.glob("*.proto"):
        old.unlink()
    (STD_SCHEMAS / "opcua_builtins.proto").write_text(HEADER + BUILTINS_PROTO, encoding="utf-8", newline="\n")
    structs, enums = collect_types()
    for enum in sorted(enums, key=lambda e: e.name):
        _write_type_file(enum.name, _enum_proto(enum))
    for st in sorted(structs, key=lambda s: s.name):
        _write_type_file(st.name, _struct_proto(st), _deps_for_struct(st))
    print(f"wrote opcua_builtins.proto to {STD_SCHEMAS} and {len(structs) + len(enums)} proto files to {SCHEMAS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
