#!/usr/bin/env python3
"""
Generate Annex B of the OPC UA Data Channels Part 6 errata: the annotated byte layout
of every wire vector.

The annex is written between the markers in
`core-specs/data-channels/OPC-UA-Part6-Data-Channel-Transport.md`, and the same
rendering is also written to `annex-wire-layouts.md` next to this script so the
validator can detect drift without reparsing the document. Do not edit between the
markers - regenerate.
"""
from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from frame_codec import (  # noqa: E402
    INLINE, annotate, check_contiguous, decode, hexdump,
)
from gen_vectors import vectors  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC_DIR = os.path.abspath(os.path.join(
    HERE, "..", "..", "..", "..", "source", "core-specs", "data-channels"))
DOCS = ("OPC-UA-Part6-Data-Channel-Transport.md", "spec.md")
SIDECAR = os.path.join(HERE, "annex-wire-layouts.md")
BEGIN = "<!-- BEGIN GENERATED: wire-layouts -->"
END = "<!-- END GENERATED: wire-layouts -->"


def _section(v: dict) -> str:
    data = v["bytes"]
    footer_size = len(v["footer"])
    spans = annotate(data, v["mode"], footer_size=footer_size)
    check_contiguous(spans, len(data))
    # Prove the vector is decodable and that the annotation describes the same frame.
    frame = decode(data, v["mode"], footer_size=footer_size)
    assert frame.channel_id == v["frame"].channel_id
    assert frame.frame_type == v["frame"].frame_type
    assert frame.payload == v["frame"].payload

    mode_label = "inline (opc.tcp, opc.wss)" if v["mode"] == INLINE else "QUIC (opc.quic)"
    # The heading carries its anchor, because the template derives the number and matches an
    # anchor exactly; a generated heading without one is a clause nothing can cite.
    anchor = re.sub(r"[^a-z0-9]+", "", v["name"].lower())
    out = [f"### {v['name']} {{#sec-{anchor}}}", "",
           f"**Framing** {mode_label} · **Frame type** `{v['frame'].type_name}` · "
           f"**ChannelId** {v['frame'].channel_id} · **Total** {len(data)} bytes", "",
           v["description"], "",
           "| Offset | Length | Section | Field | Value | Bytes |",
           "|---|---|---|---|---|---|"]
    for s in spans:
        raw = data[s.offset:s.end]
        shown = " ".join(f"{b:02X}" for b in raw[:12])
        if len(raw) > 12:
            shown += " …"
        out.append(f"| {s.offset} | {s.length} | {s.section} | `{s.field}` | "
                   f"{s.value} | `{shown}` |")
    out += ["", "```text", hexdump(data), "```"]
    return "\n".join(out)


def generate() -> str:
    vs = vectors()
    header = [
        "This annex is generated by `../extras/data-channels/tools/gen_wire_annex.py` "
        "from the reference codec in `../extras/data-channels/tools/frame_codec.py`, and "
        "the byte sequences shown are byte-for-byte the vectors published under "
        "`../extras/data-channels/examples/`. Do not edit between the markers.",
        "",
        "Every span below is verified to be contiguous and non-overlapping, and every "
        "vector is verified to decode back to the frame it was encoded from, so a table "
        "that disagrees with the bytes cannot be committed.",
        "",
        "All integers are little-endian, matching the OPC UA Binary DataEncoding.",
    ]
    return "\n".join(header) + "\n\n" + "\n\n".join(_section(v) for v in vs).rstrip() + "\n"


def main() -> int:
    rendered = generate()
    with open(SIDECAR, "w", encoding="utf-8", newline="\n") as f:
        f.write(rendered)
    for name in DOCS:
        doc = os.path.join(SPEC_DIR, name)
        if not os.path.exists(doc):
            print(f"skipped {name} (not present yet)")
            continue
        with open(doc, encoding="utf-8") as f:
            text = f.read()
        if BEGIN not in text or END not in text:
            raise SystemExit(f"wire-layouts markers not found in {doc}")
        start = text.index(BEGIN) + len(BEGIN)
        finish = text.index(END)
        new_text = text[:start] + "\n\n" + rendered + "\n" + text[finish:]
        if new_text != text:
            with open(doc, "w", encoding="utf-8", newline="\n") as f:
                f.write(new_text)
        print(f"updated {name}")
    print(f"wrote {os.path.basename(SIDECAR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
