#!/usr/bin/env python3
"""
Generator for the OPC UA — Vision worked examples.

Reads a JSON descriptor and emits, deterministically:
  * ../../../vision/<folder>/Opc.Ua.<Domain>.Vision.NodeSet2.xml  - an instance overlay
  * ../../../vision/<folder>/OPC-UA-<Domain>-Vision-Addendum.md    - the addendum

Usage (from the repo root):
    python metaverse-specs/extras/vision/tools/build_examples.py            # all descriptors
    python metaverse-specs/extras/vision/tools/build_examples.py <file.json>

Why a generator at all: the sibling openusd-binding addenda have hand-authored overlay
NodeSets with no committed generator, so their prose and their XML can drift apart. Here
the descriptor is the single source of truth for both, and the overlay is regenerated
rather than edited.

Type NodeIds are resolved by importing build_model.py, so an example can never reference
a type id that the base model does not define.
"""
from __future__ import annotations
import json
import os
import sys
import xml.sax.saxutils as sx

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_model as vm  # noqa: E402  (path set above)

VISION_NS = vm.NAMESPACE

# Base-UA NodeIds used by the overlays. Emitted through an <Aliases> block, as the
# base NodeSets in this repository do, so the XML stays readable.
ALIASES = [
    ("Boolean", "i=1"), ("Int32", "i=6"), ("UInt32", "i=7"), ("Double", "i=11"),
    ("String", "i=12"), ("LocalizedText", "i=21"),
    ("HasComponent", "i=47"), ("HasProperty", "i=46"),
    ("HasTypeDefinition", "i=40"), ("HasInterface", "i=17603"),
]

HasComponent = "HasComponent"
HasProperty = "HasProperty"
HasTypeDefinition = "HasTypeDefinition"
HasInterface = "HasInterface"
FolderType = "i=61"
PropertyType = "i=68"
BaseDataVariableType = "i=63"

# Type BrowseName -> NodeId in the Vision namespace, taken from the base model.
TYPE_ID = {n.bname: n.nid for n in vm.NODES.values()
           if n.cls in ("UAObjectType", "UADataType", "UAReferenceType")}


def vtype(name):
    if name not in TYPE_ID:
        raise SystemExit(f"unknown Vision type '{name}' - check build_model.py")
    return f"ns=2;i={TYPE_ID[name]}"


def enum_value(enum_name, field_name):
    """Resolve an enumeration field to its integer value from the base model."""
    nid = TYPE_ID.get(enum_name)
    if nid is None:
        raise SystemExit(f"unknown enumeration '{enum_name}'")
    defn = vm.NODES[nid].definition or ""
    marker = f'Name="{field_name}" Value="'
    i = defn.find(marker)
    if i < 0:
        raise SystemExit(f"'{field_name}' is not a field of {enum_name}")
    j = i + len(marker)
    return int(defn[j:defn.find('"', j)])


class Overlay:
    """Accumulates instance nodes for one example overlay."""

    def __init__(self, example_uri):
        self.example_uri = example_uri
        self.nodes = []
        self.next_id = 5001

    def _nid(self):
        v = self.next_id
        self.next_id += 1
        return v

    def obj(self, browse, typedef, parent=None, reftype=HasComponent, desc=None):
        nid = self._nid()
        refs = [(HasTypeDefinition, typedef, True)]
        if parent is not None:
            refs.append((reftype, f"ns=1;i={parent}", False))
            self._add_forward(parent, reftype, nid)
        self.nodes.append(dict(cls="UAObject", nid=nid, browse=browse, desc=desc,
                               parent=(f"ns=1;i={parent}" if parent else None),
                               refs=refs, attrs={}, value=None))
        return nid

    def folder(self, browse, parent, desc=None):
        return self.obj(browse, FolderType, parent, desc=desc)

    def prop(self, browse, datatype, value, parent, desc=None,
             typedef=PropertyType, reftype=HasProperty):
        nid = self._nid()
        refs = [(HasTypeDefinition, typedef, True),
                (reftype, f"ns=1;i={parent}", False)]
        self._add_forward(parent, reftype, nid)
        self.nodes.append(dict(cls="UAVariable", nid=nid, browse=browse, desc=desc,
                               parent=f"ns=1;i={parent}",
                               refs=refs, attrs={"DataType": datatype},
                               value=value))
        return nid

    def iface(self, node_nid, typedef):
        self._add_forward(node_nid, HasInterface, None, explicit=typedef)

    def _add_forward(self, parent, reftype, child_nid, explicit=None):
        for n in self.nodes:
            if n["nid"] == parent:
                tgt = explicit if explicit is not None else f"ns=1;i={child_nid}"
                n["refs"].append((reftype, tgt, True))
                return
        raise SystemExit(f"parent ns=1;i={parent} not found")

    def emit(self, domain):
        out = ['<?xml version="1.0" encoding="utf-8"?>',
               f'<!-- OPC UA - Vision worked example: {domain}. Generated by '
               'build_examples.py - do not edit by hand. PROVISIONAL NodeIds. -->',
               '<UANodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
               'xmlns:xsd="http://www.w3.org/2001/XMLSchema" '
               'xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" '
               'xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd">',
               '  <NamespaceUris>',
               f'    <Uri>{self.example_uri}</Uri>',
               f'    <Uri>{VISION_NS}</Uri>',
               '  </NamespaceUris>',
               '  <Models>',
               f'    <Model ModelUri="{self.example_uri}" Version="0.1.0" '
               f'PublicationDate="{vm.PUBDATE}">',
               '      <RequiredModel ModelUri="http://opcfoundation.org/UA/" '
               f'Version="{vm.BASE_UA_VERSION}" '
               f'PublicationDate="{vm.BASE_UA_PUBDATE}" />',
               f'      <RequiredModel ModelUri="{VISION_NS}" Version="{vm.VERSION}" '
               f'PublicationDate="{vm.PUBDATE}" />',
               '    </Model>',
               '  </Models>',
               '  <Aliases>']
        for name, val in ALIASES:
            out.append(f'    <Alias Alias="{name}">{val}</Alias>')
        out.append('  </Aliases>')
        for n in self.nodes:
            out.append(self._emit_node(n))
        out.append('</UANodeSet>')
        return "\n".join(out) + "\n"

    @staticmethod
    def _emit_node(n):
        a = [f'{n["cls"]} NodeId="ns=1;i={n["nid"]}"',
             f'BrowseName="1:{sx.escape(n["browse"])}"']
        if n["parent"]:
            a.append(f'ParentNodeId="{n["parent"]}"')
        if "DataType" in n["attrs"]:
            a.append(f'DataType="{n["attrs"]["DataType"]}"')
        lines = ["  <" + " ".join(a) + ">"]
        lines.append(f'    <DisplayName>{sx.escape(n["browse"])}</DisplayName>')
        if n["desc"]:
            lines.append(f'    <Description>{sx.escape(n["desc"])}</Description>')
        lines.append("    <References>")
        for rt, tgt, fwd in n["refs"]:
            fs = "" if fwd else ' IsForward="false"'
            lines.append(f'      <Reference ReferenceType="{rt}"{fs}>{tgt}</Reference>')
        lines.append("    </References>")
        if n["value"] is not None:
            lines.append("    " + n["value"])
        lines.append(f'  </{n["cls"]}>')
        return "\n".join(lines)


UAX = 'xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd"'


def v_string(s):
    return f'<Value><uax:String {UAX}>{sx.escape(str(s))}</uax:String></Value>'


def v_uint32(i):
    return f'<Value><uax:UInt32 {UAX}>{int(i)}</uax:UInt32></Value>'


def v_double(d):
    return f'<Value><uax:Double {UAX}>{float(d)}</uax:Double></Value>'


def v_bool(b):
    return (f'<Value><uax:Boolean {UAX}>'
            f'{"true" if b else "false"}</uax:Boolean></Value>')


def v_int32(i):
    return f'<Value><uax:Int32 {UAX}>{int(i)}</uax:Int32></Value>'


def v_ltext(s):
    return (f'<Value><uax:LocalizedText {UAX}>'
            f'<uax:Text>{sx.escape(str(s))}</uax:Text></uax:LocalizedText></Value>')


# Property name -> (DataType alias, value emitter). Anything not listed is a String.
DT = {
    "UInt32": ("UInt32", v_uint32),
    "Double": ("Double", v_double),
    "Boolean": ("Boolean", v_bool),
    "Int32": ("Int32", v_int32),
    "String": ("String", v_string),
    "LocalizedText": ("LocalizedText", v_ltext),
}


def put(ov, parent, name, kind, value, desc=None):
    dt, fn = DT[kind]
    return ov.prop(name, dt, fn(value), parent, desc=desc)


def put_enum(ov, parent, name, enum_name, field, desc=None):
    val = enum_value(enum_name, field)
    return ov.prop(name, f"ns=2;i={TYPE_ID[enum_name]}", v_int32(val), parent,
                   desc=desc or f"{enum_name}.{field}")


# ---------------------------------------------------------------------------
# Overlay construction
# ---------------------------------------------------------------------------
def build_media(ov, sensor, st, cl):
    """Media management object with one stream and one clip endpoint."""
    media = ov.obj("Media", vtype("VisionMediaManagementType"), sensor,
                   desc="Media endpoints and their control surface.")
    streams = ov.folder("StreamEndpoints", media)
    clips = ov.folder("ClipEndpoints", media)

    stream = ov.obj(st["name"], vtype("StreamEndpointType"), streams,
                    desc=st.get("description"))
    put(ov, stream, "EndpointId", "String", st["endpointId"])
    put(ov, stream, "EndpointUri", "String", st["endpointUri"])
    put_enum(ov, stream, "StreamProtocol", "VisionStreamProtocolEnum", st["protocol"])
    put_enum(ov, stream, "State", "VisionEndpointStateEnum", st.get("state", "Ready"))
    put_enum(ov, stream, "Authentication", "VisionEndpointAuthenticationEnum",
             st.get("authentication", "Digest"))
    if "codec" in st:
        put_enum(ov, stream, "Codec", "VisionVideoCodecEnum", st["codec"])
    for name, kind in (("Width", "UInt32"), ("Height", "UInt32"),
                       ("FrameRate", "Double")):
        key = name[0].lower() + name[1:]
        if key in st:
            put(ov, stream, name, kind, st[key])

    clip = ov.obj(cl["name"], vtype("ClipEndpointType"), clips,
                  desc=cl.get("description"))
    put(ov, clip, "EndpointId", "String", cl["endpointId"])
    put(ov, clip, "EndpointUri", "String", cl["endpointUri"])
    put_enum(ov, clip, "ClipFormat", "VisionClipFormatEnum", cl["format"])
    put_enum(ov, clip, "State", "VisionEndpointStateEnum", cl.get("state", "Ready"))
    put_enum(ov, clip, "Authentication", "VisionEndpointAuthenticationEnum",
             cl.get("authentication", "Token"))
    if "inlineDeliveryEnabled" in cl:
        put(ov, clip, "InlineDeliveryEnabled", "Boolean", cl["inlineDeliveryEnabled"])
    if "maxInlineClipSize" in cl:
        put(ov, clip, "MaxInlineClipSize", "UInt32", cl["maxInlineClipSize"])
    return media


def build_sensor(ov, name, s, sim=None):
    """One sensor instance, physical or simulated. Both take the identical shape -
    that is the sim/real symmetry the base specification requires."""
    sensor = ov.obj(name, vtype(s["type"]), desc=s.get("description"))
    if s.get("realityKind") in ("Simulated", "Hybrid"):
        ov.iface(sensor, vtype("IVisionSimulatedType"))

    put(ov, sensor, "SensorId", "String", s["sensorId"])
    put_enum(ov, sensor, "RealityKind", "VisionRealityKindEnum", s["realityKind"])
    put_enum(ov, sensor, "Modality", "VisionSensorModalityEnum", s["modality"])
    for pname, kind in (("Manufacturer", "LocalizedText"), ("Model", "LocalizedText"),
                        ("SerialNumber", "String"), ("DeviceUri", "String"),
                        ("FrameId", "String")):
        key = pname[0].lower() + pname[1:]
        if key in s:
            put(ov, sensor, pname, kind, s[key])
    if s["type"] == "ImageSensorType":
        for pname, kind in (("Width", "UInt32"), ("Height", "UInt32"),
                            ("PixelFormat", "String"), ("ExposureTime", "Double"),
                            ("Gain", "Double"), ("AcquisitionFrameRate", "Double"),
                            ("TriggerMode", "String"), ("TriggerSource", "String")):
            key = pname[0].lower() + pname[1:]
            if key in s:
                put(ov, sensor, pname, kind, s[key])

    if sim:
        put(ov, sensor, "SimulatorUri", "String", sim["simulatorUri"])
        put(ov, sensor, "StageIdentifier", "String", sim["stageIdentifier"])
        put(ov, sensor, "PrimPath", "String", sim["primPath"])
        if "groundTruthAvailable" in sim:
            put(ov, sensor, "GroundTruthAvailable", "Boolean",
                sim["groundTruthAvailable"])
        if "randomizationSeed" in sim:
            put(ov, sensor, "RandomizationSeed", "String",
                str(sim["randomizationSeed"]))
    return sensor


def build_overlay(d):
    ov = Overlay(d["exampleNamespaceUri"])
    s = d["sensor"]

    sim = d.get("simulation") if s.get("realityKind") in ("Simulated", "Hybrid") else None
    sensor = build_sensor(ov, d["instanceName"], s, sim)
    build_media(ov, sensor, d["stream"], d["clip"])

    # --- optics -------------------------------------------------------------
    if "optics" in d:
        o = d["optics"]
        optics = ov.obj("Optics", vtype("OpticsType"), sensor)
        for name in ("FocalLength", "Aperture", "WorkingDistance", "Magnification"):
            key = name[0].lower() + name[1:]
            if key in o:
                put(ov, optics, name, "Double", o[key])
        for name in ("OpticalFormat", "MountType", "LensType"):
            key = name[0].lower() + name[1:]
            if key in o:
                put(ov, optics, name, "String", o[key])

    # --- calibration --------------------------------------------------------
    if d.get("calibrations"):
        cals = ov.folder("Calibrations", sensor)
        for c in d["calibrations"]:
            cal = ov.obj(c["name"], vtype(c["type"]), cals, desc=c.get("description"))
            put(ov, cal, "CalibrationId", "String", c["calibrationId"])
            put(ov, cal, "Valid", "Boolean", c.get("valid", True))
            if "residualError" in c:
                put(ov, cal, "ResidualError", "Double", c["residualError"])
            if "method" in c:
                put(ov, cal, "Method", "String", c["method"])
            if c["type"] == "ExtrinsicCalibrationType":
                put_enum(ov, cal, "Mount", "VisionCalibrationMountEnum", c["mount"])

    # --- AI -----------------------------------------------------------------
    ai = d["ai"]
    model = ov.obj(ai["model"]["name"], vtype("AiModelType"),
                   desc=ai["model"].get("description"))
    m = ai["model"]
    put(ov, model, "ModelId", "String", m["modelId"])
    put(ov, model, "Name", "LocalizedText", m["name"])
    put(ov, model, "Version", "String", m["version"])
    for name in ("Framework", "Format", "TaskKind", "ArtifactUri"):
        key = name[0].lower() + name[1:]
        if key in m:
            put(ov, model, name, "String", m[key])

    dep = ai["deployment"]
    deployment = ov.obj(dep["name"], vtype("AiDeploymentType"),
                        desc=dep.get("description"))
    put(ov, deployment, "DeploymentId", "String", dep["deploymentId"])
    put_enum(ov, deployment, "InferenceLocation", "VisionInferenceLocationEnum",
             dep["inferenceLocation"])
    if "acceleratorKind" in dep:
        put_enum(ov, deployment, "AcceleratorKind", "VisionAcceleratorKindEnum",
                 dep["acceleratorKind"])
    if "acceleratorName" in dep:
        put(ov, deployment, "AcceleratorName", "String", dep["acceleratorName"])
    if "endpointUri" in dep:
        put(ov, deployment, "EndpointUri", "String", dep["endpointUri"])

    pl = ai["pipeline"]
    pipeline = ov.obj(pl["name"], vtype("InferencePipelineType"),
                      desc=pl.get("description"))
    put(ov, pipeline, "PipelineId", "String", pl["pipelineId"])
    put_enum(ov, pipeline, "State", "VisionEndpointStateEnum",
             pl.get("state", "Active"))
    put(ov, pipeline, "Continuous", "Boolean", pl.get("continuous", True))
    ov.folder("Results", pipeline)
    ov.obj("Feedback", vtype("VisionFeedbackType"), pipeline,
           desc="Feedback surface for corrections and overlays.")

    # --- simulated twin ------------------------------------------------------
    # Emitted with exactly the same shape as the physical sensor above. That is the
    # point: a client cannot distinguish them except by reading RealityKind.
    if "twin" in d:
        tw = d["twin"]
        twin = build_sensor(ov, tw["instanceName"], tw["sensor"], tw["simulation"])
        build_media(ov, twin, tw["stream"], tw["clip"])
        if "learningJob" in tw:
            lj = tw["learningJob"]
            dataset = ov.obj(lj["datasetName"], vtype("AiDatasetType"),
                             desc="Synthetic dataset produced from the twin.")
            put(ov, dataset, "DatasetId", "String", lj["datasetId"])
            put_enum(ov, dataset, "SourceKind", "VisionDatasetSourceEnum",
                     lj.get("sourceKind", "Synthetic"))
            job = ov.obj(lj["name"], vtype("LearningJobType"),
                         desc=lj.get("description"))
            put(ov, job, "JobId", "String", lj["jobId"])
            put_enum(ov, job, "State", "VisionLearningJobStateEnum",
                     lj.get("state", "Collecting"))

    return ov


# ---------------------------------------------------------------------------
# Addendum
# ---------------------------------------------------------------------------
def emit_addendum(d):
    s = d["sensor"]
    st = d["stream"]
    cl = d["clip"]
    ai = d["ai"]
    dep = ai["deployment"]
    rel = f"../../extras/vision/examples/{d['folder']}/{d['descriptorFile']}"
    L = []
    A = L.append
    A(f"# OPC UA {d['domain']} — Vision Addendum")
    A("")
    A(f"**Implementer annex to *OPC UA — Vision* (Release {vm.VERSION} — Draft).**")
    A("")
    A(f"> {d['summary']} The machine-readable source of truth is "
      f"[`{d['descriptorFile']}`]({rel}); this document and "
      f"`Opc.Ua.{d['domain']}.Vision.NodeSet2.xml` are both generated from it by "
      "`build_examples.py`, so prose and model cannot drift.")
    A("")
    A("---")
    A("")
    A("## 1 Scope")
    A("")
    A(d["scope"])
    A("")
    A("## 2 Normative references")
    A("")
    A("- *OPC UA — Vision*, Release " + vm.VERSION + " (the base specification), "
      "`../OPC-UA-Vision.md`.")
    for r in d.get("references", []):
        A(f"- {r}")
    A("")
    A("## 3 The sensor")
    A("")
    A("| Member | Value |")
    A("|---|---|")
    A(f"| Type | `{s['type']}` |")
    A(f"| `SensorId` | `{s['sensorId']}` |")
    A(f"| `RealityKind` | `{s['realityKind']}` |")
    A(f"| `Modality` | `{s['modality']}` |")
    for key, label in (("width", "`Width`"), ("height", "`Height`"),
                       ("pixelFormat", "`PixelFormat`"),
                       ("exposureTime", "`ExposureTime` (µs)"),
                       ("gain", "`Gain`"),
                       ("acquisitionFrameRate", "`AcquisitionFrameRate`"),
                       ("triggerMode", "`TriggerMode`"),
                       ("deviceUri", "`DeviceUri`"),
                       ("frameId", "`FrameId`")):
        if key in s:
            A(f"| {label} | `{s[key]}` |")
    A("")
    if "simulation" in d and s["realityKind"] in ("Simulated", "Hybrid"):
        sim = d["simulation"]
        A("The sensor implements `IVisionSimulatedType`, so it is addressable in the "
          "same terms as the scene it renders:")
        A("")
        A("| Member | Value |")
        A("|---|---|")
        A(f"| `SimulatorUri` | `{sim['simulatorUri']}` |")
        A(f"| `StageIdentifier` | `{sim['stageIdentifier']}` |")
        A(f"| `PrimPath` | `{sim['primPath']}` |")
        A("")
        A("`PrimPath` resolves to a `UsdGeomCameraType` instance where the Server also "
          "implements *OPC UA — OpenUSD Scene Materialization* (base specification "
          "Annex C).")
        A("")
    A("## 4 Media endpoints")
    A("")
    A("Both mandatory defaults of base specification §6.2 are present — an RTSP stream "
      "and a JPEG clip endpoint:")
    A("")
    A("| Endpoint | Type | Key members |")
    A("|---|---|---|")
    A(f"| `{st['name']}` | `StreamEndpointType` | `StreamProtocol = {st['protocol']}`, "
      f"`EndpointUri = {st['endpointUri']}` |")
    A(f"| `{cl['name']}` | `ClipEndpointType` | `ClipFormat = {cl['format']}`, "
      f"`EndpointUri = {cl['endpointUri']}` |")
    A("")
    if cl.get("inlineDeliveryEnabled"):
        A(f"This clip endpoint additionally enables the optional **Media Inline "
          f"Delivery** facet, with `MaxInlineClipSize = {cl['maxInlineClipSize']}` "
          "bytes. A client may subscribe to `LatestClip` and receive the encoded JPEG "
          "directly; if an image exceeds that bound the Server sets "
          "`Bad_EncodingLimitsExceeded` and the client falls back to "
          "`LatestClipMetadata.Uri` (base specification §6.4).")
    else:
        A("This example does **not** enable inline delivery: clips are obtained through "
          "`GetClip` and fetched from the returned `Uri`, which is the default path.")
    A("")
    if "twin" in d:
        tw = d["twin"]
        ts = tw["sensor"]
        sim = tw["simulation"]
        A("## 5 The simulated twin")
        A("")
        A(tw["note"])
        A("")
        A("| Member | Physical sensor | Simulated twin |")
        A("|---|---|---|")
        A(f"| Instance | `{d['instanceName']}` | `{tw['instanceName']}` |")
        A(f"| `RealityKind` | `{s['realityKind']}` | `{ts['realityKind']}` |")
        A(f"| Type | `{s['type']}` | `{ts['type']}` |")
        A(f"| `Width` x `Height` | `{s.get('width')}` x `{s.get('height')}` | "
          f"`{ts.get('width')}` x `{ts.get('height')}` |")
        A(f"| `PixelFormat` | `{s.get('pixelFormat')}` | `{ts.get('pixelFormat')}` |")
        A("| Media endpoints | RTSP + JPEG | RTSP + JPEG |")
        A("")
        A("The twin additionally implements `IVisionSimulatedType`:")
        A("")
        A("| Member | Value |")
        A("|---|---|")
        A(f"| `SimulatorUri` | `{sim['simulatorUri']}` |")
        A(f"| `StageIdentifier` | `{sim['stageIdentifier']}` |")
        A(f"| `PrimPath` | `{sim['primPath']}` |")
        if "groundTruthAvailable" in sim:
            A(f"| `GroundTruthAvailable` | `{str(sim['groundTruthAvailable']).lower()}` |")
        A("")
        A("`PrimPath` resolves to a `UsdGeomCameraType` instance where the Server also "
          "implements *OPC UA — OpenUSD Scene Materialization* (base specification "
          "Annex C), so the camera's aperture and focal-length attributes are both the "
          "scene description and the imaging intrinsics.")
        A("")
        A("## 6 Inference")
    else:
        A("## 5 Inference")
    A("")
    A("| Member | Value |")
    A("|---|---|")
    A(f"| Model | `{ai['model']['name']}` v`{ai['model']['version']}` "
      f"({ai['model'].get('format', 'n/a')}) |")
    A(f"| `TaskKind` | `{ai['model'].get('taskKind', 'n/a')}` |")
    A(f"| `InferenceLocation` | **`{dep['inferenceLocation']}`** |")
    if "acceleratorKind" in dep:
        A(f"| `AcceleratorKind` | `{dep['acceleratorKind']}` |")
    if "endpointUri" in dep:
        A(f"| `EndpointUri` | `{dep['endpointUri']}` |")
    A("")
    A(d["inferenceNote"])
    A("")
    n = 7 if "twin" in d else 6
    A(f"## {n} Results")
    A("")
    A(d["resultsNote"])
    A("")
    A(f"## {n + 1} Feedback")
    A("")
    A(d["feedbackNote"])
    A("")
    A(f"## {n + 2} Deliverables")
    A("")
    A("| File | Content |")
    A("|---|---|")
    A(f"| [`{d['descriptorFile']}`]({rel}) | Machine-readable descriptor (single "
      "source). |")
    A(f"| [`Opc.Ua.{d['domain']}.Vision.NodeSet2.xml`]"
      f"(Opc.Ua.{d['domain']}.Vision.NodeSet2.xml) | The generated instance overlay. |")
    A("")
    A("Regenerate from the repository root with "
      "`python metaverse-specs/extras/vision/tools/build_examples.py`.")
    return "\n".join(L).rstrip() + "\n"


def process(path):
    with open(path, encoding="utf-8") as f:
        d = json.load(f)
    d["descriptorFile"] = os.path.basename(path)
    d["folder"] = os.path.basename(os.path.dirname(os.path.abspath(path)))
    outdir = os.path.normpath(os.path.join(HERE, "..", "..", "..", "vision",
                                           d["outputFolder"]))
    os.makedirs(outdir, exist_ok=True)
    ov = build_overlay(d)
    xml_path = os.path.join(outdir, f"Opc.Ua.{d['domain']}.Vision.NodeSet2.xml")
    md_path = os.path.join(outdir, f"OPC-UA-{d['domain']}-Vision-Addendum.md")
    with open(xml_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(ov.emit(d["domain"]))
    with open(md_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(emit_addendum(d))
    print(f"{d['domain']}: {len(ov.nodes)} instance nodes -> {d['outputFolder']}/")


def main():
    args = sys.argv[1:]
    if args:
        for a in args:
            process(a)
        return 0
    root = os.path.join(HERE, "..", "examples")
    found = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for fn in sorted(filenames):
            if fn.endswith(".json"):
                found.append(os.path.join(dirpath, fn))
    for p in sorted(found):
        process(p)
    if not found:
        print("no descriptors found")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
